### ISSUE TITLE
'language_codes'. xml_flex2json.py error

### ISSUE THREAD

**Issue by xvos007** [timarkh/tsakorpus#2]
Hi! I've run into a problem:

% python xml_flex2json.py
Traceback (most recent call last):
  File "xml_flex2json.py", line 445, in <module>
    x2j.process_corpus()
  File "../src_convertors/txt2json.py", line 314, in process_corpus
    curTokens, curWords, curAnalyzed = self.convert_file(fnameSrc, fnameTarget)
  File "xml_flex2json.py", line 430, in convert_file
    textJSON['sentences'] = [s for sNode in interlinear.xpath('./paragraphs/paragraph/phrases/phrase | '
  File "xml_flex2json.py", line 432, in <listcomp>
    for s in self.process_se_node(sNode)]
  File "xml_flex2json.py", line 387, in process_se_node
    re.sub('-.*', '', element.attrib['lang']) in self.corpusSettings['language_codes']:
KeyError: 'language_codes'

What can be wrong?

**Comment by timarkh** [comment]
Hi!

Thanks for pointing this out. The FLEX XML convertor actually reauires one additional parameter called ``language_codes`` in ``conversion_settings.json``. Turns out it was not documented, which is now [fixed](https://tsakorpus.readthedocs.io/en/latest/xml_flex2json.html). Its value is a dictionary which maps ``lang`` attribute values in your FLEX XML to the values of the ``languages`` parameter. Please try adding it and check if it works that way.

**Comment by xvos007** [comment]
I listed it and now the problem is gone. But the conventor sees no tokens:
`    "languages": ["quichua", "english"],`
`    "language_codes": {"qxl": "quichua", "en": "english"},`

`Conversion to JSON finished in 0.06296968460083008 s. 0 tokens total, 0 words total.`

**Comment by timarkh** [comment]
It may be that certain convertors under certain circumstances don't count the words correctly and just say "0 tokens" even if they actually produce some output. Isn't that what happened in your case? If there are indeed no JSON files or only empty JSON files after the conversion is finished, then something is wrong either with your files or with the convertor. Could you maybe send me an excerpt of your XML file together with the contents of src_convertors/corpus/conf_conversion at timarkh@gmail.com so that I could have a look?

**Comment by timarkh** [comment]
The token counter now works properly in the FLEX XML convertor, the issue is resolved.
